### ISSUE TITLE
ERROR: "incorrectly formatted audio data"

### ISSUE THREAD

**Issue by igor-olikh** [voiceittech/VoiceIt2-C-Sharp#2]
I tried to use mp3 and wav files of different duration (2,3,4 seconds). Every time I get the following exception from this function: **CreateVoiceEnrollmentByUrl**

`{"message":"Failed to create voice enrollment for user with userId : usr_d831d783559b40dc86ea7de34c559f0b, incorrectly formatted audio data","timeTaken":"0.849s","responseCode":"IFAD","status":400}`

What can be the problem?

**Comment by StephenAkers** [comment]
Thank you for bringing this issue to our attention. The problem is related to the url that is sent and not the repo itself, so we have emailed you to follow up.
